issuer: http://localhost:5556

storage:
  type: sqlite3
  config:
    file: /var/lib/dex/dex.db

web:
  http: 0.0.0.0:5556
  allowedOrigins: ["*"]

logger:
  level: debug
  format: text

enablePasswordDB: true

staticClients:
- id: excalidraw
  redirectURIs:
  - http://localhost:3002/auth/oidc/callback
  name: Excalidraw
  secret: ${OIDC_CLIENT_SECRET:-excalidraw-secret}

staticPasswords:
- email: ${ADMIN_EMAIL:-admin@example.com}
  hash: ${ADMIN_PASSWORD_HASH}
  username: ${ADMIN_USERNAME:-admin}
  userID: "admin-001"